// ============================================================================
// ItineraryResult — Full trip view with WhatsApp share & transport costs
// ============================================================================
//
// WhatsApp is the primary coordination channel for Indian pilgrims —
// families and groups use it to share trip details, coordinate pickups,
// and plan logistics. The share button generates a concise plain-text
// summary (under 1000 chars) and opens WhatsApp's deep link.
//
// Transport costs: The backend engine already calculates per-hop
// rickshaw/walk costs between sites. This component now displays them
// inline between each site in the timeline, giving pilgrims a clear
// picture of how they'll move and what it'll cost.
// ============================================================================

import { useEffect, useState } from "react";
import { useNavigate, useParams, Link } from "react-router-dom";
import { itineraryService } from "../../services/itinerary.service";
import { exportToPDF } from '../../utils/exportToPdf';
import { Share2, Wallet } from 'lucide-react';

/**
 * Generates a WhatsApp-friendly plain text summary of the itinerary.
 * Kept under 1000 chars so it displays well in chat bubbles.
 *
 * @param {Object} itinerary - Full itinerary object from the API
 * @returns {string} Plain text summary
 */
const generateWhatsAppText = (itinerary) => {
  let text = `🛕 *${itinerary.destination} Trip*\n`;
  text += `📅 ${itinerary.days} days • 👥 ${itinerary.groupSize} travelers • 💰 ₹${itinerary.budget}\n\n`;

  itinerary.plan.forEach((day) => {
    text += `*Day ${day.day}:*\n`;
    if (day.places.length === 0) {
      text += `  Rest day\n`;
    } else {
      day.places.forEach((place) => {
        text += `  📍 ${place.name}`;
        if (place.entryFee > 0) text += ` (₹${place.entryFee})`;
        text += `\n`;
      });
    }
    text += `\n`;
  });

  text += `_Generated by Tirthing_ ✨`;

  // Keep under 1000 chars for WhatsApp readability
  if (text.length > 1000) {
    text = text.substring(0, 997) + '...';
  }

  return text;
};

const ItineraryResult = () => {
  const navigate = useNavigate();
  const { id } = useParams();
  const [itinerary, setItinerary] = useState(null);
  const [loading, setLoading] = useState(true);
  const [savedOffline, setSavedOffline] = useState(false);

  useEffect(() => {
    const fetchItinerary = async () => {
      try {
        const res = await itineraryService.getItineraryById(id);
        setItinerary(res);
      } catch (err) {
        console.error("Error fetching itinerary:", err);
        const cached = localStorage.getItem(`saved_itinerary_${id}`);
        if (cached) {
          setItinerary(JSON.parse(cached));
          setSavedOffline(true);
        }
      } finally {
        setLoading(false);
      }
    };
    fetchItinerary();
  }, [id]);

  // Save to localStorage for offline access
  useEffect(() => {
    if (itinerary && itinerary._id) {
      try {
        localStorage.setItem(
          `saved_itinerary_${itinerary._id}`,
          JSON.stringify(itinerary)
        );
        setSavedOffline(true);
      } catch {
        console.warn('Could not save itinerary to localStorage for offline access');
      }
    }
  }, [itinerary]);

  const handleDownloadPDF = () => {
    if (itinerary) exportToPDF(itinerary);
  };

  // WhatsApp share — opens the native share dialog on mobile,
  // or WhatsApp Web on desktop
  const handleWhatsAppShare = () => {
    if (!itinerary) return;
    const text = generateWhatsAppText(itinerary);
    const url = `https://wa.me/?text=${encodeURIComponent(text)}`;
    window.open(url, '_blank', 'noopener');
  };

  if (loading) return <div className="text-center mt-20 text-text-muted font-medium">Loading itinerary...</div>;

  if (!itinerary) {
    return (
      <div className="text-center mt-20">
        <h2 className="text-2xl font-bold text-text">No Itinerary Found</h2>
        <button onClick={() => navigate('/generate-itinerary')} className="mt-4 text-primary underline">
          Go back to generate
        </button>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto space-y-8 pb-12">
      {/* Header */}
      <div className="bg-surface p-6 rounded-xl shadow-sm border border-border flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-3xl font-extrabold text-text">{itinerary.destination}</h1>
          <p className="text-text-muted mt-2 font-medium bg-input-bg inline-block px-3 py-1 rounded-md border border-border text-sm">
            {itinerary.days} Days • {itinerary.groupSize} Travelers • ₹{itinerary.budget}
          </p>
        </div>

        <div className="flex items-center gap-3 flex-wrap">
          {savedOffline && (
            <span className="text-xs font-semibold text-green-700 bg-green-50 border border-green-200 px-2.5 py-1 rounded-md">
              ✓ Saved for offline
            </span>
          )}

          {/* WhatsApp share — primary coordination channel for Indian pilgrims */}
          <button
            onClick={handleWhatsAppShare}
            className="flex items-center gap-2 px-4 py-2.5 rounded-lg font-semibold text-sm border border-green-300 text-green-700 bg-green-50 hover:bg-green-100 transition-colors"
            aria-label="Share itinerary via WhatsApp"
          >
            <Share2 className="w-4 h-4" />
            WhatsApp
          </button>

          {/* Budget tracker link */}
          <Link
            to={`/trip/${itinerary._id}/tracker`}
            className="flex items-center gap-2 px-4 py-2.5 rounded-lg font-semibold text-sm border border-primary text-primary hover:bg-primary hover:text-white transition-colors"
            aria-label="Track expenses for this trip"
          >
            <Wallet className="w-4 h-4" />
            Track Expenses
          </Link>

          <button
            onClick={handleDownloadPDF}
            className="text-white px-5 py-2.5 rounded-lg font-semibold shadow-md hover:shadow-lg transition-all"
            style={{ background: 'var(--gradient-primary)' }}
          >
            Download PDF
          </button>
        </div>
      </div>

      {/* Days Mapping */}
      <div className="space-y-6">
        {itinerary.plan.map((dayPlan) => (
          <div
            key={dayPlan._id || dayPlan.day}
            className="bg-surface rounded-xl shadow-sm border border-border overflow-hidden"
          >
            {/* Day Header */}
            <div className="bg-input-bg border-b border-border px-6 py-4">
              <h3 className="text-xl font-extrabold text-primary">
                Day {dayPlan.day}
              </h3>
            </div>

            {/* Day Content */}
            <div className="p-6">
              <div className="relative border-l-2 border-primary/30 ml-3 md:ml-6 space-y-8">
                {dayPlan.places.map((place, idx) => (
                  <div key={place._id || idx}>
                    {/* Transport cost between sites — the engine calculates
                        per-hop rickshaw/walk costs, we display them here */}
                    {idx > 0 && place.transportCost != null && (
                      <div className="relative pl-6 sm:pl-8 mb-4">
                        <div className="absolute -left-[5px] top-1 w-2.5 h-2.5 rounded-full bg-border" />
                        <div className="flex items-center gap-2 text-xs text-text-muted bg-input-bg border border-border rounded-lg px-3 py-2 w-fit">
                          <span>
                            {place.transportMode === 'walk' ? '🚶' : '🛺'}
                            {place.transportMode === 'walk' ? ' Walk' : ' Rickshaw'}
                          </span>
                          {place.distanceKm != null && (
                            <span>• {place.distanceKm.toFixed(1)} km</span>
                          )}
                          {place.travelTimeMin != null && (
                            <span>• ~{Math.round(place.travelTimeMin)} min</span>
                          )}
                          {place.transportCost > 0 && (
                            <span className="font-semibold text-primary">
                              • ₹{Math.round(place.transportCost)}
                            </span>
                          )}
                        </div>
                      </div>
                    )}

                    {/* Place card */}
                    <div className="relative pl-6 sm:pl-8">
                      {/* Timeline Dot */}
                      <div className="absolute -left-[9px] top-2 w-4 h-4 rounded-full bg-primary ring-4 ring-surface" />

                      <div className="flex flex-col md:flex-row gap-5 items-start">
                        {/* Image */}
                        {place.image && (
                          <img
                            src={place.image}
                            alt={place.name}
                            className="w-full md:w-40 h-28 object-cover rounded-lg"
                            loading="lazy"
                          />
                        )}

                        {/* Content */}
                        <div className="flex-1">
                          <h4 className="text-xl font-bold text-text mb-1">
                            {place.name}
                          </h4>

                          <div className="flex flex-wrap gap-2 mt-2 mb-3">
                            <span className="px-2.5 py-1 text-xs font-semibold bg-blue-50 text-blue-700 rounded-md">
                              ⏱ {place.visitDuration} hrs
                            </span>

                            <span className="px-2.5 py-1 text-xs font-semibold bg-green-50 text-green-700 rounded-md">
                              {place.entryFee > 0
                                ? `₹${place.entryFee} Entry`
                                : "Free Entry"}
                            </span>

                            <a
                              href={`https://www.google.com/maps?q=${place.latitude},${place.longitude}`}
                              target="_blank"
                              rel="noopener noreferrer"
                              className="px-2.5 py-1 text-xs font-semibold bg-purple-50 text-purple-700 rounded-md hover:underline"
                            >
                              📍 View on Map
                            </a>
                          </div>

                          {place.description && (
                            <p className="text-text-muted text-sm leading-relaxed">
                              {place.description}
                            </p>
                          )}
                        </div>
                      </div>
                    </div>
                  </div>
                ))}

                {/* Empty State */}
                {dayPlan.places.length === 0 && (
                  <div className="pl-8 text-text-light italic font-medium">
                    No places scheduled. Rest or explore locally.
                  </div>
                )}
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default ItineraryResult;